name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Prune images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          cut-off: 1h
          image-names: "journal"
          keep-n-most-recent: 3
          rust-log: debug
          token: ${{ secrets.CONTAINER_RETENTION_POLICY_TOKEN }}
      - name: "renovatebot"
        run: |
          npm i renovatebot@38.128.3
    
