name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  "prune-old-containers":
    runs-on: ubuntu-latest
    steps:
      - name: Prune images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          cut-off: 1h
          image-names: "journal"
          keep-n-most-recent: 3
          rust-log: debug
          token: ${{ secrets.CONTAINER_RETENTION_POLICY_TOKEN }}
  "manage-dependencies":
    env:
      RENOVATE_PLATFORM: 'github'
      RENOVATE_REPOSITORIES: "https://github.com/surf-bum/journal"
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: "renovatebot"
        run: |
          npm i renovate@38.128.3
          npx renovate
    
