name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Prune images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          cut-off: 1h
          image-names: "journal"
          keep-n-most-recent: 3
          rust-log: debug
          token: ${{ secrets.GITHUB_TOKEN }}
